<?php
declare(strict_types=1);

// ShikharMobile SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

ShikharMobileUtility::setRegistrar(function (ShikharMobileUtility $u): void {
    $u->clean = [ShikharMobileClean::class, 'call'];
    $u->done = [ShikharMobileDone::class, 'call'];
    $u->make_error = [ShikharMobileMakeError::class, 'call'];
    $u->feature_add = [ShikharMobileFeatureAdd::class, 'call'];
    $u->feature_hook = [ShikharMobileFeatureHook::class, 'call'];
    $u->feature_init = [ShikharMobileFeatureInit::class, 'call'];
    $u->fetcher = [ShikharMobileFetcher::class, 'call'];
    $u->make_fetch_def = [ShikharMobileMakeFetchDef::class, 'call'];
    $u->make_context = [ShikharMobileMakeContext::class, 'call'];
    $u->make_options = [ShikharMobileMakeOptions::class, 'call'];
    $u->make_request = [ShikharMobileMakeRequest::class, 'call'];
    $u->make_response = [ShikharMobileMakeResponse::class, 'call'];
    $u->make_result = [ShikharMobileMakeResult::class, 'call'];
    $u->make_point = [ShikharMobileMakePoint::class, 'call'];
    $u->make_spec = [ShikharMobileMakeSpec::class, 'call'];
    $u->make_url = [ShikharMobileMakeUrl::class, 'call'];
    $u->param = [ShikharMobileParam::class, 'call'];
    $u->prepare_auth = [ShikharMobilePrepareAuth::class, 'call'];
    $u->prepare_body = [ShikharMobilePrepareBody::class, 'call'];
    $u->prepare_headers = [ShikharMobilePrepareHeaders::class, 'call'];
    $u->prepare_method = [ShikharMobilePrepareMethod::class, 'call'];
    $u->prepare_params = [ShikharMobilePrepareParams::class, 'call'];
    $u->prepare_path = [ShikharMobilePreparePath::class, 'call'];
    $u->prepare_query = [ShikharMobilePrepareQuery::class, 'call'];
    $u->graphql_body = [ShikharMobileGraphql::class, 'body'];
    $u->graphql_errors = [ShikharMobileGraphql::class, 'errors'];
    $u->result_basic = [ShikharMobileResultBasic::class, 'call'];
    $u->result_body = [ShikharMobileResultBody::class, 'call'];
    $u->result_headers = [ShikharMobileResultHeaders::class, 'call'];
    $u->transform_request = [ShikharMobileTransformRequest::class, 'call'];
    $u->transform_response = [ShikharMobileTransformResponse::class, 'call'];
});
